---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  namespace: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - weather
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: weather-app
          image: w3athr/weather-app:v3.3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
              ephemeral-storage: "50Mi"
            limits:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "100Mi"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: weather-configmap
            - secretRef:
                name: api-key-secret
      imagePullSecrets:
        - name: dockerhub-pat
