---
- name: Prepare
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: Install sudo and python3 using raw module
      ansible.builtin.raw: |
        apt-get update && apt-get install -y sudo python3
      changed_when: true
